# Generated by Django 5.1 on 2024-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="actors",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="director",
            field=models.TextField(null=True),
        ),
    ]
