# Generated by Django 5.1 on 2024-11-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="tmdb_id",
            field=models.IntegerField(),
        ),
    ]
