# Generated by Django 5.1 on 2024-10-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="genre_id",
        ),
        migrations.AddField(
            model_name="content",
            name="genre_ids",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="content",
            name="user_rating",
            field=models.FloatField(null=True),
        ),
    ]
