# Generated by Django 5.1 on 2024-10-11 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0002_remove_content_genre_id_content_genre_ids_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="user_rating",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
