# Generated by Django 5.1 on 2024-10-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0003_alter_content_user_rating_alter_watchlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="genres",
            field=models.TextField(null=True),
        ),
    ]
